import { db } from "./db";
import { ordensCompra, centrosCusto } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingOrdens = await db.select({ count: sql<number>`count(*)` }).from(ordensCompra);
  if (Number(existingOrdens[0].count) > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database...");

  const centros = [
    { cdCentroCusto: 101, dsCentroCusto: "TI" },
    { cdCentroCusto: 102, dsCentroCusto: "Financeiro" },
    { cdCentroCusto: 103, dsCentroCusto: "Administrativo" },
    { cdCentroCusto: 104, dsCentroCusto: "Operações" },
    { cdCentroCusto: 105, dsCentroCusto: "RH" },
  ];

  for (const centro of centros) {
    await db.insert(centrosCusto).values(centro);
  }

  const now = new Date();
  const ordens = [
    {
      nrSeqOrdemCompra: 50987,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "43587.96",
      dsCentroCusto: "Operações",
      cdCentroCusto: 104,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "CARLOS SILVA",
      nmPjFornecedor: "FORNECEDOR ABC LTDA",
      nmPessoaSolicitante: "MARIA SANTOS",
      ieUrgencia: "N",
      dsObservacao: "Material hospitalar urgente",
      nrSeqPedidoAutorizacao: 1,
    },
    {
      nrSeqOrdemCompra: 50978,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "32914.49",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "PEDRO COSTA",
      nmPjFornecedor: "TECH SOLUTIONS SA",
      nmPessoaSolicitante: "ANA LIMA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 2,
    },
    {
      nrSeqOrdemCompra: 50884,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "4718.67",
      dsCentroCusto: "RH",
      cdCentroCusto: 105,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "JOSE FERREIRA",
      nmPjFornecedor: "RH CONSULTING LTDA",
      nmPessoaSolicitante: "PATRICIA OLIVEIRA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 3,
    },
    {
      nrSeqOrdemCompra: 50845,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "42002.23",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "LUCAS MENDES",
      nmPjFornecedor: "DIGITAL CORP LTDA",
      nmPessoaSolicitante: "FERNANDA ROCHA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 4,
    },
    {
      nrSeqOrdemCompra: 50802,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "48201.61",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "MARCOS ALMEIDA",
      nmPjFornecedor: "INFOTECH SOLUÇÕES",
      nmPessoaSolicitante: "JULIANA CASTRO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 5,
    },
    {
      nrSeqOrdemCompra: 50795,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "13696.40",
      dsCentroCusto: "Financeiro",
      cdCentroCusto: 102,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "DRA. FERNANDA RIBEIRO",
      cdAprovador: "1002",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "RAFAEL SANTOS",
      nmPjFornecedor: "FINANCEIRA GLOBAL SA",
      nmPessoaSolicitante: "CAMILA DUARTE",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 6,
    },
    {
      nrSeqOrdemCompra: 50743,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "44711.05",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "THIAGO BARROS",
      nmPjFornecedor: "ADMIN SERVICES LTDA",
      nmPessoaSolicitante: "RENATA GOMES",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 7,
    },
    {
      nrSeqOrdemCompra: 50737,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "43577.53",
      dsCentroCusto: "RH",
      cdCentroCusto: 105,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "EDUARDO PEREIRA",
      nmPjFornecedor: "PESSOAS CONNECT LTDA",
      nmPessoaSolicitante: "AMANDA RIBEIRO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 8,
    },
    {
      nrSeqOrdemCompra: 50723,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "15594.20",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "DRA. FERNANDA RIBEIRO",
      cdAprovador: "1002",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "GABRIEL NUNES",
      nmPjFornecedor: "OFFICE SOLUTIONS SA",
      nmPessoaSolicitante: "BEATRIZ CARDOSO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 9,
    },
    {
      nrSeqOrdemCompra: 50807,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "18131.45",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "FELIPE ARAUJO",
      nmPjFornecedor: "CLOUD SERVICES LTDA",
      nmPessoaSolicitante: "CAROLINA MARTINS",
      ieUrgencia: "S",
      dsObservacao: "Equipamentos de TI para nova ala",
      nrSeqPedidoAutorizacao: 10,
    },
    {
      nrSeqOrdemCompra: 50649,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "50081.11",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "VITOR SOUZA",
      nmPjFornecedor: "MOVEIS HOSPITAL LTDA",
      nmPessoaSolicitante: "LARISSA PINTO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 11,
    },
    {
      nrSeqOrdemCompra: 50623,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "5047.06",
      dsCentroCusto: "Financeiro",
      cdCentroCusto: 102,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "DANIEL MOREIRA",
      nmPjFornecedor: "CONTABIL EXPRESS SA",
      nmPessoaSolicitante: "ISABELA FREITAS",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 12,
    },
    {
      nrSeqOrdemCompra: 50620,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "30342.27",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "ROBERTO LIMA",
      nmPjFornecedor: "ADMIN TECH LTDA",
      nmPessoaSolicitante: "VANESSA ALVES",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 13,
    },
    {
      nrSeqOrdemCompra: 50563,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "17894.71",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "ANDERSON COSTA",
      nmPjFornecedor: "INFRA HOSPITALAR SA",
      nmPessoaSolicitante: "DANIELA BORGES",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 14,
    },
    {
      nrSeqOrdemCompra: 50397,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "31675.25",
      dsCentroCusto: "Financeiro",
      cdCentroCusto: 102,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "PAULO VIEIRA",
      nmPjFornecedor: "FINANCE PRO LTDA",
      nmPessoaSolicitante: "TATIANA SOUZA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 15,
    },
    {
      nrSeqOrdemCompra: 50365,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "15327.36",
      dsCentroCusto: "Operações",
      cdCentroCusto: 104,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "RODRIGO MELO",
      nmPjFornecedor: "OPS MEDICAL LTDA",
      nmPessoaSolicitante: "LUCIANA CARVALHO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 16,
    },
    {
      nrSeqOrdemCompra: 50296,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "47449.03",
      dsCentroCusto: "Operações",
      cdCentroCusto: 104,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "GUSTAVO RAMOS",
      nmPjFornecedor: "LOGISTICA SAÚDE SA",
      nmPessoaSolicitante: "SIMONE NEVES",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 17,
    },
    {
      nrSeqOrdemCompra: 50133,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "10490.48",
      dsCentroCusto: "Financeiro",
      cdCentroCusto: 102,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "P",
      dsStatusAprovacao: "PENDENTE",
      nmPessoaFisicaComprador: "HENRIQUE DIAS",
      nmPjFornecedor: "SUPRIMENTOS GERAIS LTDA",
      nmPessoaSolicitante: "PRISCILA TEIXEIRA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 18,
    },
    {
      nrSeqOrdemCompra: 50910,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "8750.30",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "DRA. FERNANDA RIBEIRO",
      cdAprovador: "1002",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "BRUNO MARQUES",
      nmPjFornecedor: "NETWORK PLUS LTDA",
      nmPessoaSolicitante: "ALINE MOURA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 19,
    },
    {
      nrSeqOrdemCompra: 50850,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "22345.89",
      dsCentroCusto: "Operações",
      cdCentroCusto: 104,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "ANDRE FONSECA",
      nmPjFornecedor: "MEDIC SUPPLY SA",
      nmPessoaSolicitante: "ELIANA CORREIA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 20,
    },
    {
      nrSeqOrdemCompra: 50780,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "6890.15",
      dsCentroCusto: "Financeiro",
      cdCentroCusto: 102,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "LEANDRO CAMPOS",
      nmPjFornecedor: "AUDIT PARTNERS LTDA",
      nmPessoaSolicitante: "MONIQUE SILVA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 21,
    },
    {
      nrSeqOrdemCompra: 50700,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "35120.75",
      dsCentroCusto: "Administrativo",
      cdCentroCusto: 103,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "DRA. FERNANDA RIBEIRO",
      cdAprovador: "1002",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "MATEUS BARBOSA",
      nmPjFornecedor: "GESTÃO TOTAL SA",
      nmPessoaSolicitante: "CLAUDIA NASCIMENTO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 22,
    },
    {
      nrSeqOrdemCompra: 50650,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "19200.00",
      dsCentroCusto: "RH",
      cdCentroCusto: 105,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "DIEGO FERREIRA",
      nmPjFornecedor: "TALENT HUNT LTDA",
      nmPessoaSolicitante: "RAQUEL OLIVEIRA",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 23,
    },
    {
      nrSeqOrdemCompra: 50600,
      cdEstabelecimento: 1,
      nmEstabelecimento: "HOSPITAL SAMEL",
      vlOrdemCompra: "11450.60",
      dsCentroCusto: "TI",
      cdCentroCusto: 101,
      dtLiberacao: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 19, 12),
      hrLiberacao: "19:12",
      ieAprovReprov: "A",
      dsStatusAprovacao: "APROVADO",
      nmAprovador: "ROBERTO NASCIMENTO",
      cdAprovador: "1001",
      dtAprovReprov: new Date(),
      nmPessoaFisicaComprador: "RICARDO LOPES",
      nmPjFornecedor: "SOFT DEVELOP LTDA",
      nmPessoaSolicitante: "MARIANA AZEVEDO",
      ieUrgencia: "N",
      nrSeqPedidoAutorizacao: 24,
    },
  ];

  for (const ordem of ordens) {
    await db.insert(ordensCompra).values(ordem);
  }

  console.log(`Seeded ${centros.length} centros de custo and ${ordens.length} ordens de compra`);
}
